# Generated by Django 4.1.6 on 2023-03-22 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goa_app', '0002_destinations_season_state_delete_goa'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='season',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='goa_app.season'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinations',
            name='state',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='goa_app.state'),
            preserve_default=False,
        ),
    ]
