# Generated by Django 4.1.6 on 2023-04-03 06:53

import cloudinary.models
from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goa_app', '0003_destinations_season_destinations_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('name', models.CharField(max_length=255)),
                ('rooms', models.CharField(max_length=255)),
                ('text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('state', models.CharField(max_length=255)),
            ],
        ),
    ]
