# Generated by Django 4.1.6 on 2023-04-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goa_app', '0004_hotels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='text',
        ),
        migrations.AddField(
            model_name='hotels',
            name='food',
            field=models.TextField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
