# Generated by Django 4.1.6 on 2023-04-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goa_app', '0005_remove_hotels_text_hotels_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='rooms',
            field=models.IntegerField(),
        ),
    ]
