# Generated by Django 4.1.6 on 2023-04-03 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goa_app', '0006_alter_hotels_rooms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hotels',
            new_name='Restaurants',
        ),
    ]
