# Generated by Django 4.1.6 on 2023-04-03 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goa_app', '0007_rename_hotels_restaurants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='rooms',
            new_name='price',
        ),
    ]
