# Generated by Django 4.1.6 on 2023-04-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goa_app', '0009_login_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=255)),
                ('Last_name', models.CharField(max_length=255)),
                ('Contact_no', models.IntegerField()),
                ('Email_id', models.EmailField(max_length=254)),
                ('Message', models.TextField()),
            ],
        ),
    ]
