# Generated by Django 4.1.6 on 2023-04-23 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goa_app', '0011_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
