# Generated by Django 4.1.6 on 2023-04-23 06:32

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goa_app', '0012_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='profileimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imag', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imag')),
            ],
        ),
    ]
