# Generated by Django 4.1.6 on 2023-04-23 06:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goa_app', '0013_profileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='imag',
        ),
        migrations.AddField(
            model_name='profileimage',
            name='image',
            field=cloudinary.models.CloudinaryField(default=2, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
