# Generated by Django 4.1.6 on 2023-04-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goa_app', '0014_remove_profileimage_imag_profileimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimage',
            name='nimg',
            field=models.CharField(default=2, max_length=266),
            preserve_default=False,
        ),
    ]
